const dataResep = [
  {
    id: 1,
    nama: "Tahu Goreng",
    bahan: [
      "tahu",
      "bawang putih",
      "bawang merah",
      "garam",
      "ketumbar",
      "minyak",
    ],
    langkah: ["Potong tahu", "Rendam tahu dengan bumbu", "goreng"],
    kategori: "Tahu",
  },
  {
    id: 2,
    nama: "Tempe Goreng",
    bahan: ["tempe", "bawang putih", "garam", "ketumbar", "minyak"],
    langkah: ["Iris tempe", "Rendam tahu dengan bumbu", "Goreng"],
    kategori: "Tempe",
  },
  {
    id: 3,
    nama: "Telur Dadar Sayur",
    bahan: ["telur", "daun bawang", "garam", "merica", "minyak"],
    langkah: [
      "Pecahkan telur",
      "Tambahkan daun bawang",
      "Tambahkan garam & merica",
      "Kocok hingga merata",
      "Goreng",
    ],
    kategori: "Telur",
  },
  {
    id: 4,
    nama: "Ayam Goreng",
    bahan: [
      "ayam",
      "bawang putih",
      "bawang merah",
      "ketumbar",
      "garam",
      "minyak",
    ],
    langkah: [
      "Lumuri ayam dengan bumbu",
      "Diamkan hingga bumbu meresap",
      "Goreng",
    ],
    kategori: "Ayam",
  },
  {
    id: 5,
    nama: "Sup Ayam",
    bahan: [
      "ayam",
      "wortel",
      "kubis",
      "bawang putih",
      "bawang merah",
      "garam",
      "merica",
      "daun bawang",
      "seledri",
    ],
    langkah: [
      "Rebus air hingga mendidih",
      "Masukkan ayam tunggu hingga matang",
      "Masukkan wortel dan kubis",
      "Bumbui",
      "Tambahkan daun bawang & seledri",
    ],
    kategori: "Sayur",
  },
  {
    id: 6,
    nama: "Tumis Kangkung",
    bahan: [
      "kangkung",
      "bawang putih",
      "bawang merah",
      "cabai",
      "garam",
      "saus tiram",
      "minyak",
      "kecap",
    ],
    langkah: [
      "Tumis bawang merah, bawang putih, cabai",
      "Masukkan kangkung",
      "Tambahkan garam",
      "Tambahkan saus tiram & kecap",
      "Aduk hingga merata",
    ],
    kategori: "Sayur",
  },
  {
    id: 7,
    nama: "Mie Goreng Telur",
    bahan: [
      "mie",
      "telur",
      "kecap",
      "bawang putih",
      "bawang merah",
      "garam",
      "cabai",
      "minyak",
    ],
    langkah: [
      "Rebus mie",
      "Tumis Bumbu",
      "Masukkan telur",
      "Masukkan mie",
      "Tambahkan kecap",
      "Aduk hingga merata",
    ],
    kategori: "Mie",
  },
  {
    id: 8,
    nama: "Perkedel Kentang",
    bahan: [
      "kentang",
      "telur",
      "bawang putih",
      "bawang merah",
      "garam",
      "merica",
      "minyak",
      "daun bawang",
    ],
    langkah: [
      "Goreng kentang kemudian haluskan",
      "Campur kentang dengan bumbu",
      "Tambahkan daun bawang & kuning telur",
      "Bentuk menjadi bulat",
      "Celupkan pada putih telur & goreng",
    ],
    kategori: "Kentang",
  },
  {
    id: 9,
    nama: "Tempe Orek",
    bahan: [
      "tempe",
      "kecap",
      "cabai",
      "bawang putih",
      "bawang merah",
      "gula",
      "garam",
      "minyak",
    ],
    langkah: [
      "Iris tempe tipis-tipis",
      "Goreng tempe hingga matang, kemudian angkat",
      "Haluskan bumbu",
      "Tumis bumbu",
      "Tambahkan tempe yang sudah digoreng",
      "Tambahkan kecap",
      "Aduk hingga merata",
    ],
    kategori: "Tempe",
  },
  {
    id: 10,
    nama: "Telur Balado",
    bahan: [
      "telur",
      "cabai",
      "tomat",
      "bawang merah",
      "bawang putih",
      "garam",
      "gula",
      "minyak",
    ],
    langkah: [
      "Rebus telur kemudian kupas",
      "Buat bumbu balado",
      "Tumis bumbu hingga matang",
      "Tambahkan telur yang sudah dikupas",
      "Aduk hingga merata",
    ],
    kategori: "Telur",
  },
  {
    id: 11,
    nama: "Sayur Bening Bayam",
    bahan: ["bayam", "jagung", "bawang merah", "garam", "bawang putih"],
    langkah: ["Rebus air hingga mendidih", "Masukkan jagung & bayam", "Bumbui"],
    kategori: "Sayur",
  },
  {
    id: 12,
    nama: "Sambal Tomat",
    bahan: [
      "tomat",
      "cabai",
      "bawang merah",
      "bawang putih",
      "garam",
      "minyak",
    ],
    langkah: [
      "Goreng bawang merah & bawang putih",
      "Goreng tomat",
      "Ulek",
      "Tumis hingga putih",
    ],
    kategori: "Sambal",
  },
  {
    id: 13,
    nama: "Tahu Bacem",
    bahan: [
      "tahu",
      "gula merah",
      "ketumbar",
      "bawang putih",
      "garam",
      "kecap",
      "air asam jawa",
    ],
    langkah: [
      "Rebus air hingga mendidih",
      "Masukkan bumbu & tahu",
      "Tambahkan kecap",
      "Ungkep",
      "Goreng",
    ],
    kategori: "Tahu",
  },
  {
    id: 14,
    nama: "Ayam Kecap",
    bahan: [
      "ayam",
      "kecap",
      "bawang putih",
      "bawang merah",
      "gula",
      "garam",
      "merica",
    ],
    langkah: [
      "Haluskan bumbu terlebih dahulu",
      "Tumis bumbu hingga matang",
      "Masukkan ayam dan tunggu hingga matang",
      "Tambahkan kecap",
      "Aduk hingga merata",
    ],
    kategori: "Ayam",
  },
  {
    id: 15,
    nama: "Sayur Asem",
    bahan: [
      "jagung",
      "kacang panjang",
      "wortel",
      "kubis",
      "asam",
      "bawang merah",
      "cabai",
      "garam",
    ],
    langkah: [
      "Rebus air hingga mendidih",
      "Masukkan sayuran",
      "Masukkan bumbu",
      "Tunggu hingga matang",
    ],
    kategori: "Sayur",
  },
  {
    id: 16,
    nama: "Tumis Buncis",
    bahan: [
      "buncis",
      "bawang putih",
      "bawang merah",
      "garam",
      "cabai",
      "minyak",
      "kecap",
    ],
    langkah: [
      "Tumis bawang merah, bawang putih & cabai",
      "Masukkan buncis",
      "Tambahkan kecap",
      "Aduk hingga merata",
    ],
    kategori: "Sayur",
  },
  {
    id: 17,
    nama: "Tempe Bacem",
    bahan: [
      "tempe",
      "gula merah",
      "ketumbar",
      "bawang putih",
      "garam",
      "kecap",
    ],
    langkah: [
      "Rebus air hingga mendidih",
      "Masukkan bumbu, gula merah & tempe",
      "Tambahkan kecap",
      "Ungkep",
      "Goreng",
    ],
    kategori: "Tempe",
  },
  {
    id: 18,
    nama: "Nasi Goreng",
    bahan: [
      "nasi",
      "telur",
      "kecap",
      "bawang putih",
      "bawang merah",
      "garam",
      "cabai",
    ],
    langkah: [
      "Tumis bumbu hingga matang",
      "Masukkan telur",
      "Tambahkan nasi",
      "Tambahkan kecap",
      "Aduk hingga merata",
    ],
    kategori: "Nasi",
  },
  {
    id: 19,
    nama: "Capcay Sayur",
    bahan: [
      "wortel",
      "pakcoy",
      "brokoli",
      "kacang kapri",
      "bawang putih",
      "bawang merah",
      "garam",
      "saus tiram",
    ],
    langkah: [
      "Tumis bumbu hingga matang",
      "Masukkan sayur",
      "Aduk hingga merata kemudian tambahkan saus tiram",
    ],
    kategori: "Sayur",
  },
  {
    id: 20,
    nama: "Soto Ayam",
    bahan: [
      "ayam",
      "bawang putih",
      "bawang merah",
      "jahe",
      "kunyit",
      "serai",
      "merica",
      "ketumbar",
      "garam",
    ],
    langkah: [
      "Rebus air hingga mendidih",
      "Rebus ayam",
      "Masukkan bumbu",
      "Tunggu hingga matang",
    ],
    kategori: "Ayam",
  },
  {
    id: 21,
    nama: "Sayur Sop",
    bahan: [
      "wortel",
      "kentang",
      "kubis",
      "bawang putih",
      "bawang merah",
      "garam",
      "merica",
    ],
    langkah: [
      "Rebus air hingga mendidih",
      "Masukkan sayuran",
      "Tambahkan bumbu dan tunggu hingga matang",
    ],
    kategori: "Sayur",
  },
  {
    id: 22,
    nama: "Oseng Tempe Pedas",
    bahan: ["tempe", "cabai", "bawang merah", "bawang putih", "kecap", "garam"],
    langkah: [
      "Tumis bumbu hingga matang",
      "Masukkan tempe",
      "Tambahkan kecap & aduk hingga merata",
    ],
    kategori: "Tempe",
  },
  {
    id: 23,
    nama: "Telur Bali",
    bahan: [
      "telur",
      "kunyit",
      "bawang putih",
      "bawang merah",
      "cabai",
      "merica",
      "ketumbar",
      "garam",
    ],
    langkah: [
      "Rebus telur kemudian kupas",
      "Tumis bumbu hingga matang",
      "Masukkan telur",
      "Aduk hingga merata",
    ],
    kategori: "Telur",
  },
  {
    id: 24,
    nama: "Sambal Goreng Kentang",
    bahan: [
      "kentang",
      "cabai",
      "bawang putih",
      "bawang merah",
      "garam",
      "minyak",
    ],
    langkah: [
      "Goreng kentang terlebih dahulu",
      "Buat sambal",
      "Tumis sambal",
      "Masukkan kentang",
      "Aduk hingga merata",
    ],
    kategori: "Kentang",
  },
  {
    id: 25,
    nama: "Sayur Lodeh",
    bahan: [
      "labu",
      "kacang panjang",
      "santan",
      "bawang putih",
      "bawang merah",
      "garam",
      "cabai",
    ],
    langkah: [
      "Rebus air hingga mendidih",
      "Masukkan labu siam dan kacang panjang",
      "Masukkan bumbu",
      "Masukkan santan",
    ],
    kategori: "Sayur",
  },
  {
    id: 26,
    nama: "Tumis Sawi Putih",
    bahan: [
      "sawi putih",
      "bawang putih",
      "bawang merah",
      "garam",
      "cabai",
      "minyak",
      "kecap",
    ],
    langkah: [
      "Tumis bawang merah, bawang putih, & cabai",
      "Masukkan sawi",
      "Tambahkan kecap",
      "Aduk hingga merata",
    ],
    kategori: "Sayur",
  },
  {
    id: 27,
    nama: "Ayam Bakar",
    bahan: ["ayam", "bawang putih", "ketumbar", "merica", "kecap", "cabai"],
    langkah: [
      "Haluskan bumbu terlebih dahulu",
      "Ungkep ayam dengan bumbu hingga matang",
      "Bakar ayam yang telah dibumbui",
    ],
    kategori: "Ayam",
  },
  {
    id: 28,
    nama: "Tahu Kuah Kuning",
    bahan: [
      "tahu matang",
      "kunyit",
      "bawang putih",
      "bawang merah",
      "garam",
      "cabai",
      "santan",
    ],
    langkah: [
      "Tumis bumbu hingga matang",
      "Tambahkan tahu",
      "Tambahkan air hingga mendidih",
      "Tambahkan santan",
      "Aduk hingga merata",
    ],
    kategori: "Tahu",
  },
  {
    id: 29,
    nama: "Mie Kuah Telur",
    bahan: [
      "mie",
      "telur",
      "bawang putih",
      "bawang merah",
      "garam",
      "merica",
      "cabai",
    ],
    langkah: [
      "Tumis bumbu hingga matang",
      "Tambahkan telur",
      "Tambahkan air dan masukkan mie",
      "Aduk hingga merata",
    ],
    kategori: "Mie",
  },
  {
    id: 30,
    nama: "Telur Kecap",
    bahan: [
      "telur",
      "kecap",
      "bawang putih",
      "bawang merah",
      "garam",
      "gula",
      "cabai",
      "merica",
      "ketumbar",
    ],
    langkah: [
      "Rebus telur kemudian kupas",
      "Tumis bumbu hingga matang",
      "Masukkan telur",
      "Tambahkan kecap",
      "Aduk hingga merata",
    ],
    kategori: "Telur",
  },
];
